name: Build Native Binary
run-name: Build Native Binary
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y podman openjdk-19-jdk-headless
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: ./mvnw quarkus:build -Dnative
      - name: Rename Build Artifact
        run: mv target/cyshot-*-runner target/cyshot
      - name: Store Build Result
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: |
            target/cyshot
